apiVersion: apps/v1
kind: Deployment
metadata:
  name: freediameter-deployment
  namespace: ubm-diameter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: freediameter
  template:
    metadata:
      labels:
        app: freediameter
    spec:
      initContainers:
        - name: wait-for-config
          image: busybox
          command: ["sh", "-c", "while [ ! -f /etc/freediameter/freeDiameter.conf ]; do echo 'Waiting for ConfigMap...'; sleep 2; done"]
          volumeMounts:
            - name: config-volume
              mountPath: /etc/freediameter
      containers:
        - name: freediameter
          image: 519139470698.dkr.ecr.ap-southeast-1.amazonaws.com/diameterimage
          env:          
            - name: GY_APPLICATION_ID
              value: "16777238"
          ports:
            - containerPort: 5868  # Diameter port
          volumeMounts:
            - name: config-volume
              mountPath: /etc/freediameter
        - name: envoy
          image: envoyproxy/envoy:v1.29-latest
          ports:
            - containerPort: 15868
            - containerPort: 9901  # optional admin port
          volumeMounts:
            - name: envoy-config
              mountPath: /etc/envoy
          
      volumes:
        - name: config-volume
          configMap:
            name: freediameter-config
        - name: envoy-config
          configMap:
            name: envoy-config    
