apiVersion: v1
kind: ConfigMap
metadata:
  name: envoy-config
  namespace: ubm-diameter  # change if you're deploying in another namespace
data:
  envoy.yaml: |
    static_resources:
      listeners:
      - name: listener_15868
        address:
          socket_address:
            address: 0.0.0.0
            port_value: 15868
        filter_chains:
        - filters:
          - name: envoy.filters.network.tcp_proxy
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.network.tcp_proxy.v3.TcpProxy
              stat_prefix: fd_tcp
              cluster: gemba-dev-eks

      clusters:
      - name: gemba-dev-eks
        connect_timeout: 1s
        type: STATIC
        lb_policy: ROUND_ROBIN
        load_assignment:
          cluster_name: gemba-dev-eks
          endpoints:
          - lb_endpoints:
            - endpoint:
                address:
                  socket_address:
                    address: 127.0.0.1
                    port_value: 5868

    admin:
      access_log_path: "/tmp/admin_access.log"
      address:
        socket_address:
          address: 0.0.0.0
          port_value: 9901
