apiVersion: v1
kind: Service
metadata:
  name: freediameter-envoy
  namespace: ubm-diameter
spec:
  type: LoadBalancer
  ports:
    - port: 15868
      targetPort: 15868
      protocol: TCP
  selector:
    app: freediameter